name: MessageCommands
author: BauHD
version: 3.1.0
main: dev.bauhd.messagecommands.bootstrap.spigot.SpigotBootstrap
description: Plugin that creates commands to send messages.
website: https://www.spigotmc.org/resources/61780
api-version: 1.13